version: "3.10"

services:

  flask:
    build: ./flask
    container_name: flask
    image: tschneiderak/mileagerun:flask
    restart: always
    env_file:
      - .env
    expose:
      - 8080


  nginx:
    build: ./nginx
    container_name: nginx
    image: tschneiderak/mileagerun:nginx
    restart: always
    ports:
      - "80:80"

