version: "3.10"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=FlaskTest
      - DB_KEY=TestKey
    env_file:
      - .env
    expose:
      - 8080


  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

